services:
    database:
        image: mysql:latest
        ports:
            - 3306:3306
        volumes: 
            - db_data:/var/lib/mysql
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: tgdb
            MYSQL_PASSWORD: tgdb
            MYSQL_DATABASE: tgdb
            
    telegrambot:
        depends_on:
            - database
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            BOT_USERNAME: 
            BOT_TOKEN: 
            DATABASE_URL: jdbc:mysql://database:3306
            DATABASE_NAME: tgdb
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: tgdb
volumes:
    db_data: {}
